export const santoral = [
	[
		'María, Madre de Dios',
		'Basilio, Gregorio',
		'Genoveva',
		'Yolando, Rigoberto',
		'Emilia',
		'Wilma, Melanio',
		'Raimundo',
		'Luciano, Eladio',
		'Lucrecia',
		'Gonzalo',
		'Alejandro',
		'Julián',
		'Hilario',
		'Félix',
		'Raquel, Mauro',
		'Marcelo',
		'Antonio, Guido',
		'Prisca - Priscila',
		'Mario',
		'Sebastián, Fabián',
		'Inés',
		'Laura Vicuña, Vicente',
		'Virginia',
		'Francisco de Sales',
		'Elvira',
		'Timoteo, Tito, Paula - Paola',
		'Ángela Merici',
		'Tomás de Aquino',
		'Valerio',
		'Martina',
		'Juan Bosco, Marcela'
	],
	[
		'Severiano',
		'Presentación del Señor',
		'Blas, Oscar',
		'Gilberto',
		'Agueda',
		'Doris, Pablo Miki',
		'Gastón',
		'Jerónimo Emiliano, Jacqueline',
		'Rebeca',
		'Escolástica',
		'N.Sra. de Lourdes',
		'Panfilio, Pamela',
		'Beatriz',
		'Cirilo, Metodio, Valentino',
		'Fausto-ino, Jovita',
		'Samuel',
		'Alexis',
		'Bernardita',
		'Álvaro',
		'Eleuterio, Claudio',
		'Pedro Daminán, Severino',
		'Eleonora, Nora',
		'Florencio',
		'Rubén, Sergio',
		'Néstor',
		'Augusto',
		'Leandro, Gabriel Dol',
		'Román'
	],
	[
		'Rosendo',
		'Lucio',
		'Celedonio',
		'Ariel',
		'Olivia',
		'Elcira',
		'Perpétua, Felicidad',
		'Juan de Dios',
		'Francisca Romana',
		'Macario',
		'Eulogio',
		'Norma',
		'Rodrigo',
		'Matilde',
		'Luisa de Marillac',
		'Heriberto',
		'Patricio',
		'Cirilo',
		'José',
		'Alejandra',
		'Eugenia',
		'Lea',
		'Dimas',
		'Elba, Catalina de Suecia',
		'Anunciación',
		'Braulio',
		'Ruperto',
		'Octavio',
		'Gladys',
		'Artemio',
		'Benjamín, Balbina'
	],
	[
		'Hugo',
		'Sandra, Francisco de Paula',
		'Ricardo',
		'Isidoro',
		'Vicente Ferrer',
		'Edith',
		'Juan Bautista de La Salle',
		'Constanza',
		'Demetrio',
		'Ezequiel',
		'Estanislao',
		'Arnoldo, Julio',
		'Martín, Aída',
		'Máximo',
		'Crescente',
		'Flavio',
		'Leopoldo, Aniceto',
		'Wladimir',
		'Ema',
		'Edgardo',
		'Anselmo',
		'Karina',
		'Jorge',
		'Fidel',
		'Marcos',
		'Cleto, Marcelino',
		'Zita, Toribio de Mogrovejo',
		'Valeria',
		'Catalina de Siena',
		'Amador, Pío V'
	],
	[
		'José Obrero',
		'Atanasio, Boris',
		'Santa Cruz',
		'Felipe y Santiago',
		'Judit',
		'Eleodoro',
		'Domitila',
		'Segundo',
		'Isaías',
		'Antonino-a, Solange',
		'Estela',
		'Pancracio, Nereo, Aquiles',
		'N.S. Fátima',
		'Matías',
		'Isidro, Denise',
		'Honorato',
		'Pascual Bailón',
		'Erica, Corina',
		'Yvo-ne',
		'Bernardino de Siena',
		'Constantino',
		'Rita',
		'Desiderio',
		'María Auxiliadora, Susana',
		'Beda, Gregorio, Ma.Magdalena de Pazzi',
		'Mariana',
		'Emilio, Agustín de Cantorbery',
		'Germán',
		'Maximiano, Hilda',
		'Fernando/Hernán, Juana de Arco, Lorena',
		'Visitación'
	],
	[
		'Justino, Juvenal',
		'Marcelino, Erasmo',
		'Maximiliano, Carlos Lwanga',
		'Frida',
		'Bonifacio, Salvador',
		'Norberto',
		'Claudio',
		'Armando',
		'Efraín',
		'Paulina',
		'Bernabé, Trinidad',
		'Onofre',
		'Antonio',
		'Eliseo',
		'Leonidas, Manuela, Micaela',
		'Aurelio',
		'Ismael',
		'Salomón',
		'Romualdo',
		'Florentino',
		'Raul, Rodolfo, Luís Gonzaga',
		'Paulino de Nola, Tomás Moro, Juan Fisher',
		'Marcial',
		'Juan Bautista',
		'Guillermo',
		'Pelayo',
		'Cirilo',
		'Ireneo',
		'Pedro y Pablo',
		'Adolfo'
	],
	[
		'Ester',
		'Gloria',
		'Tomás',
		'Isabel, Eliana, Liliana',
		'Antonio-María, Berta',
		'María Goretti',
		'Fermín',
		'Eugenio',
		'Verónica',
		'Elías',
		'Benito',
		'Filomena',
		'Teresa de los Andes, Enrique, Joel',
		'Camilo de Lelis',
		'Buenaventura, Julio/a',
		'Carmen',
		'Carolina',
		'Federico',
		'Arsenio',
		'Marina',
		'Daniel',
		'María Magdalena',
		'Brigida',
		'Cristina',
		'Santiago',
		'Joaquín, Ana',
		'Natalia',
		'Celso',
		'Marta',
		'Abdón y Senén',
		'Ignacio de Loyola'
	],
	[
		'Alfonso María de Ligorio',
		'Eusebio',
		'Lydia',
		'Juan María Vianney',
		'Osvaldo, Nieves',
		'(Transfiguración)',
		'Sixto, Cayetano',
		'Domingo de Guzmán',
		'Justo',
		'Lorenzo',
		'Clara de Asís',
		'Laura',
		'Víctor',
		'Maximiliano Kolbe, Alfredo',
		'Asunción',
		'Esteban de Hungría, Roque',
		'Jacinto',
		'Alberto Hurtado, Elena, Nelly, Leticia',
		'Mariano',
		'Bernardo',
		'Pío X, Graciela',
		'María Reina',
		'Donato',
		'Bartolomé',
		'Luís (rey), José Calasanz',
		'Teresa de Jesús Jornet e Ibars, César',
		'Mónica',
		'Agustín',
		'Juan Bautista, Sabina',
		'Rosa de Lima',
		'Ramón'
	],
	[
		'Arturo',
		'Moisés',
		'Gregorio Magno',
		'Irma',
		'Victorino',
		'Eva, Evelyne',
		'Regina',
		'Natividad de la Virgen',
		'Sergio y Omar',
		'Nicolás de Tolentino, Adalberto',
		'Orlando, Rolando',
		'María',
		'Juan Crisóstomo',
		'Imelda',
		'N. Sra. de Dolores',
		'Cornelio, Cipriano',
		'Roberto Belarmino',
		'José de Cupertino',
		'Jenaro',
		'Amelia, Andrés Kim y Pablo Tung',
		'Mateo',
		'Mauricio',
		'Lino y Tecla',
		'N. Sra. del Carmen',
		'Aurelio',
		'Cosme y Damián',
		'Vicente de Paul',
		'Wenceslao',
		'Miguel, Gabriel y Rafael',
		'Jerónimo'
	],
	[
		'Teresita del Niño Jesús',
		'Angeles Custodios',
		'Gerardo',
		'Francisco de Asís',
		'Flor',
		'Bruno',
		'N. Sra. del Rosario',
		'N. Sra. de Begoña',
		'Dionisio - Juan Leonardi',
		'Francisco de Borja',
		'Soledad',
		'N. Sra. del Pilar',
		'Eduardo',
		'Calixto',
		'Teresa de Avila',
		'Eduvigis, Margarita Ma. Alacoque',
		'Ignacio de Antioquía',
		'Lucas',
		'Pablo de la Cruz, Renato',
		'Irene',
		'Úrsula',
		'Sara',
		'Juan Capistrano, Remigio',
		'Antonio Ma. Claret',
		'Olga',
		'Darío',
		'Gustavo',
		'Simón, Judas',
		'Narciso',
		'Alonso',
		'Quintin'
	],
	[
		'Todos los Santos',
		'Todos los Fieles difuntos',
		'Martín de Porres',
		'Carlos Borromeo',
		'Silvia',
		'Leonardo',
		'Ernesto-ina',
		'Ninfa, Godofredo',
		'Teodoro',
		'León Magno',
		'Martín de Tours',
		'Cristián',
		'Diego',
		'Humberto',
		'Alberto Magno',
		'Margarita, Gertrudis',
		'Isabel de Hungría',
		'Elsa',
		'Andrés Avelino',
		'Edmundo',
		'Presentación de la Virgen',
		'Cecilia',
		'Clemento, Columbano',
		'Flora, Andrés Dung-Lac',
		'Catalina Labouré',
		'Delfina',
		'Virgilio',
		'Blanca',
		'Saturnino',
		'Andrés'
	],
	[
		'Florencia',
		'Viviana',
		'Francisco Javier',
		'Juan Damaceno, Bárbara',
		'Ada',
		'Nicolás',
		'Ambrosio',
		'Inmaculada Concepción',
		'Jéssica',
		'N. Sra. de Loreto, Eulalia',
		'Dámaso',
		'N. Sra. de Guadalupe',
		'Lucía',
		'Juan de la Cruz',
		'Reinaldo',
		'Alicia',
		'Lázaro',
		'Sonia',
		'Urbano',
		'Abrahám, Isaac, Jacob',
		'Pedro Canisio',
		'Fabiola',
		'Victoria',
		'Adela',
		'Natividad del Señor (Noel, Noelia)',
		'Esteban',
		'Juan',
		'Stos. Inocentes',
		'Tomás Becket, David',
		'Rogelio',
		'Silvestre'
	]
];
